/**:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: none
      i_pipeline_type: RGBD
    pipeline_gen:
      i_enable_imu: true
    imu:
      i_message_type: IMU
      i_enable_rotation: true
      i_acc_freq: 400
      i_gyro_freq: 400
      i_rot_freq: 400
    rgb:
      i_disable_node: true
      i_simulate_from_topic: true
      i_publish_topic: false
    left:
      i_publish_topic: true
    right:
      i_publish_topic: true
